### ISSUE TITLE
Feature Request: find all kustomization.yaml files and iterate datree kustomize test on each one

### ISSUE THREAD

**Issue by HariSekhon** [datreeio/action-datree#11]
Similar to what I have done in my Jenkins library here:

https://github.com/HariSekhon/Jenkins/blob/master/vars/datree.groovy#L81

I think this would be a handy thing for this action to do and would be better handled inside the action than having to call the action a bunch of times incurring build overheads each time.

I also think that it may be between difficult to impossible to do a for loop on found `kustomization.yaml` files and call the action for each one with a different path, which is why I thought his might be better handled inside the action.

This would allow dynamically finding and scanning all the `kustomization.yaml` in a single github actions workflow.

Otherwise adding hardcoded explicit steps calling the action for each `kustomization.yaml` is impractical and difficult to maintain, and almost certainly going to fall out of sync with repo contents.

**Comment by eyarz** [comment]
We heard similar feedback also regarding helm:
https://github.com/datreeio/helm-datree/issues/40

If I have 5 `kustomization.yaml` files in a dir, should Datree provide one output for 5 `kustomization.yaml` files or 5 outputs, each for one `kustomization.yaml` file?

**Comment by HariSekhon** [comment]
I think it should probably be one unified output, because this will result in less boilerplate output and may reduce pushing earlier kustomizations' results off of the screen.

The end summary stats would also make more sense to be combined into one result if scanning several kustomizations together.

If you wanted them individually, you could still target each kustomization individually with separate runs.

**Comment by eyarz** [comment]
Thinking out loud here - so what we can do is to find all `kustomization.yaml` files in a dir and create a temp file that will be assembled from all the manifests we generated. We can then pass this temp file to Datree, and this will provide the user the option to scan multiple `kustomization.yaml` files in one dir with a single output.

The only thing that I don't like about this solution is when I think about the DX when a rule is failing.
It will be really hard for the user to understand which `kustomization.yaml` should be fixed.

**Comment by HariSekhon** [comment]
Yeah I'm not keen on that idea because when it trips, I'll be left scratching my head where that broken yaml is and grepping.

Ideally a tool should pinpoint for you automatically so you can go straight to the root cause, this is part of key criteria of automation to save human time, which compounds over time.

It would be better for datree run against each `kustomization.yaml` and keep track of which issues were generated in which kustomization run, so it can aggregate stats, but keep direct pointer references to the offending `kustomization.yaml`... I appreciate this will probably be more coding work and almost certainly require changes to `datree` itself.

In the short term in this action it'd be fine to just iterate each `kustomization.yaml` and live with scrolling the longer output because at least when you see the problem, the `kustomization.yaml` path should be printed next to it.

Just have to make sure that any non-zero exit status for a `datree` run is captured and reset to error exit code at the end.

**Comment by eyarz** [comment]
I gave it some more thinking, and I think I have a good solution for this one.
We are always trying to balance what is expected to be supported by Datree and what should be solved as a workaround by our users.

In this case (also apply for Helm), the balance is tricky because I understand the need, but on the other hand, this behavior is NOT supported by the templating tools themself.

Therefore, I think the best way to solve it is by making the temp file that is already generated by Datree (when using Kustomize or Helm) accessible and customized:
1. accessible - we will not delete the temp file after running `datree test` so the user will be able to review it
2. customized - the user can choose where to save the file and how to name it

This way, the user can iterate over a dir, pass relvent helm chart dir/kustomize.yaml files to Datree (with this new flag that will also generate and keep the manifest itself), and capture the status code (like you suggested). 
Datree's output will show the user the file name as it was set by him, so he can still easily trace back which resource cause the failure.

Becasue my solution requires some extra scripting, we also provide the basic bash script example for iterting over a dir and extarcting files that will be passed to Datree, together with capturing exit code.

I think this solution is the right balance.

**Comment by HariSekhon** [comment]
It'd be better from a usability perspective to list the path to the original kustomization - trawling a huge temp file is not as convenient.

I'd output the kustomization source before the results so the user could determine where to go in his actual git tree to fix it, without having to trawl the temp file and then grep for where that resource came from.

**Comment by HariSekhon** [comment]
I just rustled a script up quickly to solve this:

https://github.com/HariSekhon/DevOps-Bash-tools/blob/master/kubernetes/datree_kustomize_all.sh

You can cannibalize it if you want for this action.

**Comment by hadar-co** [comment]
@HariSekhon the script works great and seems to provide a good solution for the issue raised here 👍🏼

One thing though - the script has dependencies on other files in your repo (for example the function `check_env_defined`). If users will try to copy it as it and use it - it will not work.

Do you mind removing the dependencies? Alternatively, we can copy the script and remove them ourselves, and of course give you credit in every place we post it (docs, github action repo, etc.)

Thanks:)

**Comment by HariSekhon** [comment]
Yes that repo is designed to be cloned whole and run from within the project - it has a bunch of script libraries that are shared between many scripts for some of the more advanced shared functionality.

You can just copy line 47 onwards to avoid the `--help` and other frills if you want to copy/paste it with no dependencies.

**Comment by hadar-co** [comment]
@HariSekhon great, thank you:)

**Comment by eyarz** [comment]
added to docs:
https://hub.datree.io/integrations/kustomize-support#testing-multiple-kustomizations
