### ISSUE TITLE
datree-action fails to work with schema-location

### ISSUE THREAD

**Issue by gilbahat** [datreeio/action-datree#19]
Hi,

for one reason or another, the added schema location is ignored when running datree through the action.

CLI output:

✗ datree kustomize test apps/staging --schema-version "1.24.0" --schema-location "https://raw.githubusercontent.com/gilbahat/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json"

(...)

(Summary)

- Passing YAML validation: 1/1

- Passing Kubernetes (1.24.0) schema validation: 1/1

- Passing policy check: 1/1

Github action output:

Run datreeio/action-datree@main
  with:
    isKustomization: true
    path: apps/staging
    cliArguments: --schema-version 1.24.0 --schema-location "https://raw.githubusercontent.com/gilbahat/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json"
    isHelmChart: false
  env:
    DATREE_TOKEN: ***

(...)

❌  k8s schema validation error: For field spec: Additional property rolloutStrategy is not allowed

please advise.

**Comment by gilbahat** [comment]
note that since the CRD catalog has updated since, this particular example can no longer be reconstructed

**Comment by hadar-co** [comment]
@gilbahat is this the failure you're referring to?
`❌ k8s schema validation error: For field spec: Additional property rolloutStrategy is not allowed`

If so, the schema is found successfully but it is violated - since schema validation runs in strict mode by default, which prohibits additional properties.

In the latest CLI version, you can pass the `--permissive-schema` flag to disable strict mode and allow additional properties.
